### ISSUE TITLE
i don't know what to call this bug...

### ISSUE THREAD

**Issue by S0LiD-ST4T3** [dvdvideo1234/TrackAssemblyTool#11]
375253 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_PHYSGUN: Extension disabled
375254 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_GHOSTS: (gmod_tool) Swep other
375255 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_GHOSTS: Hook mismatch
375256 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_RADMENU: (gmod_tool) Swep other
375257 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_RADMENU: Hook mismatch
375258 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_PHYSGUN: Extension disabled
375259 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_GHOSTS: (gmod_tool) Swep other
375260 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_GHOSTS: Hook mismatch
375261 [01-03-19 11:36:30] CLIENT > TRACKASSEMBLY [SQL] DRAW_RADMENU: (gmod_tool) Swep other...

Keeps going FOREVER in console... can't see legitimate output...

I'll see if i can force a crash on the engine and include the latest dump.

**Comment by S0LiD-ST4T3** [comment]
it could be my grav/physgun replacer, no bloody idea.

**Comment by Mates** [comment]
I have the same issue. These messages just keep spamming my console many times a second. I tried removing the .gma file as well as deleting the TRACKASSEMBLY tables from cl.db to no avail.

**Comment by S0LiD-ST4T3** [comment]
That says =it all...

THIS ADDON SUCKS DONKEY BALLS in stability!

**Comment by dvdvideo1234** [comment]
@S0LiD-ST4T3 , @Mates 

These are just print-outs and logs. Don't worry about that. :+1:  I have placed these especially to trace when someone else is calling my hooks. This can well be ignored.

If you don't want the logs to be printed you can follow [this guide](https://github.com/dvdvideo1234/TrackAssemblyTool/wiki/Technical-information#is-there-any-feature-which-can-be-used-to-control-which-log-messages-can-show-up-and-which-will-not) and create [this here file](https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/data/trackassembly/trackasmlib_slskip.txt) and put it inside [`...garrysmod/data/trackassembly`](https://github.com/dvdvideo1234/TrackAssemblyTool/tree/master/data/trackassembly) (a.k.a. Where the log file is located) to prevent such log messages to be shown in the logs. The program will open this file and automatically load it during gmod load time, processing the list of the ignored logs and storing them in a hash table.

**Please keep in mind that the log messages are for debug purposes only!**

**Comment by Mates** [comment]
I have tried creating and putting the provided `trackasmlib_slskip.txt` on both server and client to no avail - the console keeps spamming the debug messages. Strange thing is this doesn't seem to happen to other players. I then tried with an empty `trackasmlib_slonly.txt` (also on both server and client) with the same result. Additionally, when I try to do the Factory reset as described [here](https://github.com/dvdvideo1234/TrackAssemblyTool/wiki/Factory-reset), I get the following errors when I click the `Reset variables` button:
```
[ERROR] lua/autorun/trackassembly_init.lua:360: attempt to call method 'SetAsmConvar' (a nil value)
  1. unknown - lua/autorun/trackassembly_init.lua:360
   2. unknown - lua/includes/modules/concommand.lua:54

[ERROR] lua/trackassembly/trackasmlib.lua:2593: attempt to index global 'defTab' (a nil value)
  1. RemoveDSV - lua/trackassembly/trackasmlib.lua:2593
   2. unknown - lua/autorun/trackassembly_init.lua:381
    3. unknown - lua/includes/modules/concommand.lua:54
```
Any way I can help debug this? If it helps, I am running Linux Mint 19.1

You also mentioned there should be a log file at `...garrysmod/data/trackassembly`, but there is nothing there - the folder gets created on server startup, but there never is anything in it (not counting the files I put there).

**Comment by dvdvideo1234** [comment]
@Mates 

Thank you for the report. I will push it to steam this evening.

You do not need to do anything ;)

**Comment by dvdvideo1234** [comment]
More about the logging stream you can find in this page:

https://github.com/dvdvideo1234/TrackAssemblyTool/wiki/How-to-control-the-logs-output-stream

**Comment by dvdvideo1234** [comment]
Sorry that I noticed just recently. It was quite a ride at work this month...

**Comment by dvdvideo1234** [comment]
Prepared and committed to steam. Thank you @Mates, @S0LiD-ST4T3

**Comment by Mates** [comment]
Ah, I see, so I wasn't just being delusional :) nice work, I'll give it a try hopefully tomorrow and let you know if I happen to stumble upon any other issues.

**Comment by dvdvideo1234** [comment]
Thank you again! Please do that everything should be fine now since your server will refresh itself from the workshop :1st_place_medal:
