### ISSUE TITLE
Bug with Track assemble Tool 

### ISSUE THREAD

**Issue by Fitzganch** [dvdvideo1234/TrackAssemblyTool#30]
after attempting to fix another issue with track assembly. 
I can see the track in the tool options and see the ghosted prop but it will not spawn

https://user-images.githubusercontent.com/63378466/115440189-76ecb200-a1dd-11eb-92c0-e09b193eb8fc.mp4

**Comment by dvdvideo1234** [comment]
I will take a look at it tomorrow. Don't worry. In the meantime spawn somewhere else :smile_cat:

**Comment by dvdvideo1234** [comment]
Hi,

It appears that I do not have this map. The latest I have from [`Magnum`](https://github.com/MagnumMacKivler) is the newest newest new [`gm_sunsetgulch.bsp`](https://steamcommunity.com/sharedfiles/filedetails/?id=311697867), but I do not have such trees or bridges shown in your bug report. It is most likely that there is some map stuff in the way ( as I notice that track piece becomes a bit darker at this spawn point ) and TA default behavior forbids players to spawn stuff outside the map bounds ( like the floor or walls for example ). Can you provide me the map that you are using. In the meantime you can disable the option by turning off the restriction. It is possible to crash the server when you spawn outside of map bounds though. Small chance there, but still not zero ;)
![image](https://user-images.githubusercontent.com/9112662/115824744-1645bb00-a411-11eb-8ddb-cbab932db52f.png)

**Comment by dvdvideo1234** [comment]
@Fitzganch 

Since I did not get any response for more than a week, I will assume that you have successfully managed to disable the bounding mode for your narrow use case. I am closing this.
