### ISSUE TITLE
[BUG] Remove line(s) of code causing "Do not rush context menu"

### ISSUE THREAD

**Issue by VCSoldier** [dvdvideo1234/TrackAssemblyTool#33]
**Describe the bug**
Not a bug, this is just really annoying, and completely un-needed

**To Reproduce**
1. Spawn two bridge props
2. hold c
3. go across both really quickly

**Expected behavior**
Not wanting it to spam my notifications
**Screenshots**
![image](https://user-images.githubusercontent.com/50423227/139952300-65bcbabf-9d01-42ad-b19c-3b386ac1c871.png)

**Host machine (please complete the following information):**
 - OS type: Windows
 - OS version: 10
 - Gmod platform:PC
 - Gmod branch: x64-x86
 - Gmod version: 2021-11-01
 - Gmod instance: 
 - Tool version: 8.671

**Additional context**
why is this even needed, at all, this is a useless line of code

**Comment by dvdvideo1234** [comment]
Hi, this is needed for security reasons. This represents a client hooks that [sends stuff to the server to execute here](https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/autorun/trackassembly_init.lua#L1396). You can set `trackassemby_dtmessage` to `0` but this may trigger a security risk of someone being able to execute the hook many times in a second. The client can send anything server side will potentially crash the server. That is the true reason of coding this time delta call. Disable the option at your own risk. 👍 I may reduce the call of the notification to draw it only once when it is encountered.

**Comment by dvdvideo1234** [comment]
Now `15` seconds need to pass since the first trigger of the security notification. Routine will be executed on every `trackassemby_dtmessage` seconds and the message will be displayed every 15 seconds after the first trigger when the player is still persistent to flood. Cheers! Commited and pushed to steam!
