### ISSUE TITLE
[BUG] Text shows up as "Oops, missing ?"

### ISSUE THREAD

**Issue by wrefgtzweve** [dvdvideo1234/TrackAssemblyTool#34]
**Describe the bug**
All text in the tool is "Oops, missing?"

**To Reproduce**
1. Subscribe to TAT
2. Open tool
3. All text is "Oops, missing?"

**Expected behavior**
My american friends can see the text on tool menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/69946827/144153477-c31424ff-a5cb-4124-878d-d1057aeb373e.png)

**Host machine (please complete the following information):**
 - OS type: Windows
 - OS version: 10
 - Gmod branch: x64
 - Gmod version: 2021.11.01
 - Gmod instance: CLIENT
 - Tool version: Latest workshop version

**Additional context**
I feel like this could be some kind of localization issue? I'm from the netherlands if that matters, yet i don't seem to have issues with other addons.

**Comment by dvdvideo1234** [comment]
If the language is not found the description must default to English. I am telling the server to [send the translations file to the client here](https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/autorun/trackassembly_init.lua#L343). The tool script [passes the language code here](https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/trackassembly/trackasmlib.lua#L4915) and later [initializes it by compiling the file](https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/trackassembly/trackasmlib.lua#L4895) content to create a function. The order of execution will always be: `init` (send translations) then `tool` (init localify). For starters you can [try enable the logs](https://github.com/dvdvideo1234/TrackAssemblyTool/wiki/How-to-control-the-logs-output-stream) and attach the output of: `InitLocalify` `GetLocalify` and `GetPhrase`.

Meanwhile I will try testing it with other code different than `N/A`.

**Comment by dvdvideo1234** [comment]
@wrefgtzweve Latest change is pushed to steam. Please reopen the issue if it still persists.
