### ISSUE TITLE
[BUG] attempt to index global 'asmlib' (a nil value), serverside error

### ISSUE THREAD

**Issue by wrefgtzweve** [dvdvideo1234/TrackAssemblyTool#35]
**Describe the bug**
This errors happens at least daily on serverside, unknown what's directly causing it as we've not been able to replicate it yet. If i remember correctly we're using the workshop version.
```
lua/trackassembly/trackasmlib.lua:2424: attempt to index global 'asmlib' (a nil value)
```

**To Reproduce**
X

**Expected behavior**
X

**Screenshots**
X

**Host machine (please complete the following information):**
Gmod dedicated server linux 64x-86x

**Additional context**

**Comment by dvdvideo1234** [comment]
First of all, `thanks`.. TA is growing to be very large and feature rich addon ;)

Done! Try now. If it works and it probably will ( while looking at the symptoms  ) I will close this. Will be closed automatically in couple of days when no comments are made. Refresh your server from the `WS` and try again ;)

https://steamcommunity.com/sharedfiles/filedetails//changelog/287012681/

**Comment by dvdvideo1234** [comment]
Apparently this comes from this commit and thank you for finding it! https://github.com/dvdvideo1234/TrackAssemblyTool/commit/e077a9ef27142895fa331a2781bbd4b3dde9b020
