### ISSUE TITLE
[BUG] Clientside lua error

### ISSUE THREAD

**Issue by wrefgtzweve** [dvdvideo1234/TrackAssemblyTool#36]
**Describe the bug**
Players are getting this clientside error whenever they're using the tool, im not sure how to reproduce it as i haven't had it myself.

```
lua/entities/gmod_ent_ttc/cl_init.lua:185: attempt to call method 'UpdateLinks' (a nil value)
  1. func - lua/entities/gmod_ent_ttc/cl_init.lua:185
   2. unknown - lua/includes/extensions/net.lua:33
   0.  func - lua/entities/gmod_ent_ttc/cl_init.lua:185
    1.  unknown - lua/includes/extensions/net.lua:33
```

**Host machine (please complete the following information):**
Gmod dedicated server linux 64x-86x

**Comment by dvdvideo1234** [comment]
Neat. Thanks will look tomorrow as it is getting late.

**Comment by dvdvideo1234** [comment]
Hmm this does not really look like something TA calls. I was able to [trace this to here](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/net.lua#L33) and `net.Incoming` is not used inside the `net` library. Also it is not found in the whole TA addons folder (For `UpdateLinks` the result is the same):
![image](https://user-images.githubusercontent.com/9112662/159139288-75cb3cd4-8ea6-4bad-b480-84d2a561fca1.png)
```
Searching 84 files for "Incoming" (case sensitive)
0 matches
```

Are you really sure this is not related to SENT `lua/entities/gmod_ent_ttc/cl_init.lua:185` ?

**Comment by dvdvideo1234** [comment]
Here I've described the project structure for convenience and I do not find any of my `Lua` files here:
https://github.com/dvdvideo1234/TrackAssemblyTool/wiki/Technical-information#how-is-the-project-structured

I think this is rather a infinite recurse problem like the one I had with the [prop cannon for bombs triggering recursive explosion](https://github.com/dvdvideo1234/PropCannonTool/commit/421a19b8fc2f06fa9dd8982b36f20d19103eda6d) for non-yet-exploded bullets.

**Comment by wrefgtzweve** [comment]
That's stupid of me, I read TTC and instantly assumed train track tool, not sure what imagined the C was from. My bad!

**Comment by wrefgtzweve** [comment]
Oh now i see, i messed up and accidentally mis remebered it, it's the tank track tool not the train track tool 🤦‍♂️

**Comment by dvdvideo1234** [comment]
No worries ;)
