### ISSUE TITLE
[BUG] Shinji85's Rails Train Pack Cant Spawn

### ISSUE THREAD

**Issue by siravijbb** [dvdvideo1234/TrackAssemblyTool#42]
**Describe the bug**
It seems that some people and I can't spawn Shinji85's Rails Train Pack in Server Game mode,
And If I tried to spawn at the addon menu and it works.
**To Reproduce**
1. Started GMOD server (srcds.exe.)
2. Use the Track assembly tool to spawn Shinji85's Rails Train Pack.
3. srcds log "The Perseveranceused the tool trackassembly on models/props_phx/trains/tracks/track_1x.mdl"  No Error outputed and no track were spawn for Shinji85's Rails but other track are fine.
**Expected behavior**
No track for Shinji85's Rails Spwan. If played in single player still work fine. No restriction were set to block track,Run on as superadmin role then nothing can be locked.
**Screenshots**

**Host machine (please complete the following information):**
 - OS type: Windows 11
 - OS version: 21H2
 - Gmod platform: PC,PC(server side)
 - Gmod branch: x86-64 for client side,for server-side not sure but it seem to be default 4000. 
 - Gmod version: 2022.07.13
 - Gmod instance: yellow for server
 - Tool version: Lastest

**Additional context**
[Server collection:](https://steamcommunity.com/sharedfiles/filedetails/?id=1918380823)

**Comment by siravijbb** [comment]
Didn't try #26

**Comment by siravijbb** [comment]
It worked!!!, Maybe pin this issue for future this problem!

**Comment by dvdvideo1234** [comment]
@siravijbb 

It is already pinned for the exact same reason ;)
