### ISSUE TITLE
[BUG] Some clients hard-crash with this addon installed due to a "Model not found" error, with a model this addon doesnt even have

### ISSUE THREAD

**Issue by marchc1** [dvdvideo1234/TrackAssemblyTool#54]
**Describe the bug**
Garry's Mod clients on x86-64 seem to immediately hard-crash with this addon installed on the server. It is inconsistent (I do not get this issue, but other friends do, despite the fact they use x86-64). It complains about not being able to load a model that this addon doesnt even have, but then fails to load error.mdl immediately after.

I have an issue on the Garry's Mod issue tracker for it: https://github.com/Facepunch/garrysmod-issues/issues/5798
I'll be updating that as I get more info, I don't have solid reproduction steps at the moment.

I isolated it to this addon by having one of the friends affected
- Join with the addon installed on the server
- Still crash
- Join with the addon uninstalled with no other changes immediately after
- No longer crash

**Comment by marchc1** [comment]
Forgot to put this here too:

```
Executable: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    0. SetModel - [C]:-1
      1. MakeEntityNone - lua/trackassembly/trackasmlib.lua:2103
        2. GetTransformOA - lua/trackassembly/trackasmlib.lua:2199
          3. RegisterPOA - lua/trackassembly/trackasmlib.lua:2236
            4. (null) - lua/autorun/trackassembly_init.lua:1686
              5. pcall - [C]:-1
                6. Record - lua/trackassembly/trackasmlib.lua:2964
                  7. ImportDSV - lua/trackassembly/trackasmlib.lua:3507
                    8. ProcessDSV - lua/trackassembly/trackasmlib.lua:3771
                      9. (null) - lua/weapons/gmod_tool/stools/trackassembly.lua:95
                        10. include - [C]:-1
                          11. (null) - gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:154
                            12. include - [C]:-1
                              13. (null) - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:372
                                14. include - [C]:-1
                                  15. (null) - gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:11

  Server
    Lua Interface = NULL

  MenuSystem
	*Not in Lua call OR Lua has panicked*
```

**Comment by Grocel** [comment]
I suspect the the tools spawns every model it knows as an entity (class: `prop_physics` as from `ENTITY_DEFCLASS`) to calculate and cache the coordinates for attachments and bones. If true this would be a very bad design that fills up the model cache or slots in the model cache string table. Avoid using dummy entities.

It likely has other side effects too. One case I have observed that the dummy entities also appear in save games, because `eNone.DoNotDuplicate = true` is missing.

The code linked below, suggest it could indeed the case:
https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/trackassembly/trackasmlib.lua#L2085C1-L2105C4

**Comment by marchc1** [comment]
I finally have a way to replicate this:

- Place the contents of this ZIP into your data folder. 
[trackassembly_broken.zip](https://github.com/Facepunch/garrysmod-issues/files/14624980/trackassembly_broken.zip)
- Start the game on the x86-64 beta
- Join a server/start a game with Track Assembly installed
- Crash

**Comment by Grocel** [comment]
In the other issue (https://github.com/Facepunch/garrysmod-issues/issues/5798) the problem has been isolated to be caused from a call like this on x86-64:
```ents.CreateClientProp("models/some/invalid/model.mdl")```

Maybe add a cached `file.Exist` based model check to the entity dummy function, or redesign the tool to not relay on dummy entities, cached model or cached attachments.

**Comment by dvdvideo1234** [comment]
@marchc1 

Please try the Ghosts control dev branch:
https://github.com/dvdvideo1234/TrackAssemblyTool/tree/ghost-cnt

And tell me if it fixed the problem.

**Comment by dvdvideo1234** [comment]
Confirmed in Discord being fixed from @marchc1 

https://github.com/dvdvideo1234/TrackAssemblyTool/commit/3c39afa095bf0cb705f8a733b5612f3dd8a799f2
